### ISSUE TITLE
Telemetry-only Phoenix support

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir-phoenix#57]
When we released AppSignal for Phoenix, we had to jump through some hoops to make instrumentation work. One of these was having to wrap the code for all requests coming in, which we do by overriding the main app’s `call/2` function.

With [Telemetry](https://hexdocs.pm/telemetry/readme.html) and the instrumentation hooks how added to the Phoenix library, we’ve been able to remove some of the AppSignal-specific code we add (most recently with the template instrumentation for Phoenix 1.7 added in https://github.com/appsignal/appsignal-elixir-phoenix/pull/54).

Our next step is the override of the `call/2` function. Removing that removes the need for any updates to the code, meaning AppSignal can hook into most Phoenix apps without any more configuration. In practice, this means the `use Appsignal.Phoenix` line can be omitted.

### Requested via support

While not directly requested through support, this change was sparked by an issue we ran into in https://github.com/appsignal/appsignal-elixir-plug/pull/30. That pull request is made to make it easier to find where missing samples go (for support issues like https://github.com/appsignal/support/issues/217) by giving each span a default name ("[unknown request]”). 

This exposed that [the integration currently relies on nameless spans being dropped](https://github.com/appsignal/support/issues/217#issuecomment-1375661467). We looked into that for a bit, but since a specific fix for that required changes to the API, it’d make more sense to pull this change forward and remove the `call/2` override altogether.

We’re picking this up to make debugging issues like these easier in the future.

### Tasks

- [x] Implement performance samples through Telemetry only
- [x] Implement error samples through Telemetry only 
- [x] Span attributes
  - [x] name 
  - [x] category
  - [x] params
  - [x] sample data
  - [x] session data
- [x] Throw warning about removing `use Appsignal.Phoenix` 
- [x] [Docs update](https://github.com/appsignal/appsignal-docs/pull/1032)
- [x] [Blogpost outline](https://github.com/appsignal/appsignal-nextjs-blog/pull/758) 

### Docs

The docs change should remove the `use Appsignal.Phoenix` line from the [Phoenix install guide](https://docs.appsignal.com/elixir/integrations/phoenix.html). It should also have a note saying this only works from AppSignal for Phoenix version 2.3.0 onward. 

We’ll make sure users can upgrade without taking the `use Appsignal.Phoenix` line out. Leaving it in won’t do anything for the new version (as its responsibilities are now handled by the Telemetry-based instrumentation), but they’ll throw a warning suggesting the line to be removed. No breaking changes.

### Blog

We’re publishing a blogpost about this change, which will talk about adopting Telemetry completely. It’s [scheduled for the 31st of January](https://airtable.com/appJ9XizJrVHmN9wW/tblftx6FuIa4SAgPI/viwJf2udGZ84crew3/recaiJ4YIu53y1CBJ?blocks=hide&date=2023-01-12&mode=month).

**Comment by jeffkreeftmeijer** [comment]
Through working on this issue, I found that what I originally wanted to do will work, but not for pure Plug apps. Therefor, in https://github.com/appsignal/appsignal-elixir-phoenix/pull/56, we’re implementing this change for Phoenix specifically.

The issue here is that although we can get endpoint start and -stop events from `Plug.Telemetry`, there’s currently no way to catch errors through Telemetry alone. In Phoenix, there’s an event for that we can hook into.

By implementing this change for Phoenix, we’re able to remove the dependency on `AppSignal.Plug`. The Plug library will remain as is for now.

**Comment by jeffkreeftmeijer** [comment]
Closed by #56.
